CREATE TABLE ACCOUNT (
	NO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	IMAGE_PATH VARCHAR(200),
	IS_VERIFIED TINYINT(1) DEFAULT 0,
	ACCESS_TOKEN VARCHAR(250),
	REFRESH_TOKEN VARCHAR(250),
	REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HASH (
	NO INT PRIMARY KEY NOT NULL,
	DIGEST CHAR(64),
	SALT CHAR(32),

	FOREIGN KEY(NO)
	REFERENCES ACCOUNT(NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BOGEUM (
	NO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USER_NO INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	FOREIGN KEY(USER_NO)
	REFERENCES ACCOUNT(NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BOGEUM_MEMBER (
	NO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	BOGEUM_NO INT NOT NULL,
	ACCOUNT_NO INT NOT NULL,
	NAME VARCHAR(50),
	
	FOREIGN KEY(BOGEUM_NO)
	REFERENCES BOGEUM(NO) ON DELETE CASCADE ON UPDATE CASCADE,
	
	FOREIGN KEY(ACCOUNT_NO)
	REFERENCES ACCOUNT(NO) ON DELETE CASCADE ON UPDATE CASCADE
);